### ISSUE TITLE
"no icons"

### ISSUE THREAD

**Issue by mariomadproductions** [GerbilSoft/mcrecover#1]
gcbanner.exe says there is no icon in the opening.bnr files I try. These games do have animated save icons if you save and look at the save files in the main program (mcrecover.exe)
e.g. Super Mario Sunshine (USA)

**Comment by GerbilSoft** [comment]
GameCube opening.bnr files only have the 96x32 banner that's displayed on the "Press Start" screen. The save file icon isn't stored in a fixed location on GameCube discs.

**Comment by mariomadproductions** [comment]
I see. Are there any common locations with first-party titles (boot.dol?)

**Comment by GerbilSoft** [comment]
Closing because gcbanner is no longer included. Use [ROM Properties](https://github.com/GerbilSoft/rom-properties) instead.
